"use client";

import Image from "next/image";
import { ArrowUpRight, Github } from "lucide-react";
import { useLanguage } from "../context/LanguageContext";

type Localized = { fr: string; en: string };
type Project = {
  title: string;
  type: Localized;
  category: Localized;
  description: Localized;
  image: string;
  stack: string[];
  live: string;
  github?: string;
  role: Localized;
  result: Localized;
  concept?: boolean;
};

const projects: Project[] = [
  { title: "Theme Maestro", type: { fr: "Shopify App", en: "Shopify App" }, category: { fr: "SaaS", en: "SaaS" }, description: { fr: "Une application permettant aux marchands Shopify de planifier et automatiser les changements de thème de leur boutique.", en: "An app that lets Shopify merchants schedule and automate theme changes for their stores." }, image: "/image/themeMeastro1.png", stack: ["React", "Polaris", "GraphQL"], live: "https://apps.shopify.com/maestro-theme-scheduler", role: { fr: "Développement Full Stack", en: "Full Stack development" }, result: { fr: "[À COMPLÉTER : résultat mesurable]", en: "[TO COMPLETE: measurable result]" } },
  { title: "Flink Marketplace", type: { fr: "E-commerce", en: "E-commerce" }, category: { fr: "Full Stack", en: "Full Stack" }, description: { fr: "Une marketplace construite autour du catalogue, des vendeurs, du paiement et des échanges entre les différents acteurs de la plateforme.", en: "A marketplace built around catalogs, sellers, payments and interactions between platform users." }, image: "/image/flink1.png", stack: ["Next.js", "Laravel", "Redis", "Stripe"], live: "https://flink.ma/", github: "https://github.com/Abdelmounaim08/FlinkApp", role: { fr: "Développement Full Stack", en: "Full Stack development" }, result: { fr: "[À COMPLÉTER : résultat mesurable]", en: "[TO COMPLETE: measurable result]" } },
  { title: "Al Jabr School", type: { fr: "Éducation", en: "Education" }, category: { fr: "Full Stack", en: "Full Stack" }, description: { fr: "Un écosystème digital combinant présentation de l'établissement et outils pour structurer l'expérience des équipes et des apprenants.", en: "A digital ecosystem combining the school's presentation with tools for teams and learners." }, image: "/image/aljaber.png", stack: ["Next.js", "Laravel", "MySQL"], live: "https://ecolealjabr.com/", github: "https://github.com/Abdelmounaim08/Aljabr_Ecole", role: { fr: "Développement Full Stack", en: "Full Stack development" }, result: { fr: "[À COMPLÉTER : résultat mesurable]", en: "[TO COMPLETE: measurable result]" } },
  { title: "Mecainfo", type: { fr: "Plateforme digitale", en: "Digital platform" }, category: { fr: "WordPress · Elementor", en: "WordPress · Elementor" }, description: { fr: "Une plateforme dédiée aux professionnels de la réparation automobile, structurée autour des données techniques et des services proposés aux ateliers.", en: "A platform for automotive repair professionals, structured around technical data and services for workshops." }, image: "/image/mecainfo.png", stack: ["WordPress", "Elementor", "WooCommerce"], live: "https://www.mecainfo.com/", role: { fr: "Intégration et développement", en: "Integration and development" }, result: { fr: "[À COMPLÉTER : résultat mesurable]", en: "[TO COMPLETE: measurable result]" } },
  { title: "Logicat AR", type: { fr: "Site vitrine", en: "Marketing website" }, category: { fr: "WordPress · Elementor", en: "WordPress · Elementor" }, description: { fr: "Une expérience digitale en arabe pensée pour présenter les solutions de Logicat avec une navigation fluide et une interface adaptée au marché arabophone.", en: "An Arabic digital experience presenting Logicat solutions with fluid navigation and an interface adapted to Arabic-speaking audiences." }, image: "/image/logicat-ar.png", stack: ["WordPress", "Elementor", "JavaScript"], live: "https://ar.logicat.ma/", role: { fr: "Développement et intégration", en: "Development and integration" }, result: { fr: "[À COMPLÉTER : résultat mesurable]", en: "[TO COMPLETE: measurable result]" } },
  { title: "CoworkPro", type: { fr: "Coworking", en: "Coworking" }, category: { fr: "WordPress · Elementor", en: "WordPress · Elementor" }, description: { fr: "Un site moderne pour présenter et valoriser des espaces de coworking à Meknès, avec une expérience orientée conversion et réservation.", en: "A modern site presenting coworking spaces in Meknes, with an experience focused on conversion and booking." }, image: "/image/coworkpro.png", stack: ["WordPress", "Elementor", "CSS"], live: "https://www.coworkpro.ma/", role: { fr: "Développement web", en: "Web development" }, result: { fr: "[À COMPLÉTER : résultat mesurable]", en: "[TO COMPLETE: measurable result]" } },
  { title: "ChargeGo", type: { fr: "Mobilité électrique", en: "Electric mobility" }, category: { fr: "WordPress · Elementor", en: "WordPress · Elementor" }, description: { fr: "Une expérience web dédiée aux solutions de recharge électrique, conçue pour présenter clairement les produits et accompagner le parcours utilisateur.", en: "A web experience for electric charging solutions, designed to present products clearly and support the user journey." }, image: "/image/chargego.png", stack: ["WordPress", "Elementor", "WooCommerce"], live: "https://www.chargego.ma/", role: { fr: "Développement et intégration", en: "Development and integration" }, result: { fr: "[À COMPLÉTER : résultat mesurable]", en: "[TO COMPLETE: measurable result]" } },
  { title: "Cannabis Company", type: { fr: "Expérience de marque", en: "Brand experience" }, category: { fr: "Web Design", en: "Web Design" }, description: { fr: "Une expérience web immersive construite autour d'une identité visuelle premium et d'une présentation éditoriale responsive.", en: "An immersive web experience built around a premium visual identity and responsive editorial presentation." }, image: "/image/canabis.png", stack: ["Next.js", "Prisma", "Tailwind CSS"], live: "https://canabis-template.vercel.app/home", github: "https://github.com/Abdelmounaim08/Canabis-Template", concept: true, role: { fr: "Concept design", en: "Concept design" }, result: { fr: "[À COMPLÉTER : résultat mesurable]", en: "[TO COMPLETE: measurable result]" } },
];

export default function Project() {
  const { language, t } = useLanguage();
  const text = (value: Localized) => value[language];
  const [featuredProject, ...otherProjects] = projects;
  return <section id="projects" className="scroll-mt-24 relative overflow-hidden bg-[#0b0724] px-5 py-24 text-[#faf8ff] sm:px-8 lg:px-12 lg:py-32">
    <div className="relative mx-auto max-w-7xl">
      <div className="reveal grid gap-8 md:grid-cols-[1.3fr_1fr] md:items-end"><h2 className="text-4xl font-black leading-[0.98] tracking-[-0.04em] sm:text-5xl lg:text-[3.75rem]">{projects.length} {language === "fr" ? "projets, une seule exigence" : "projects, one requirement"}: <span className="text-white/35">{language === "fr" ? "rendre le produit évident." : "make the product obvious."}</span></h2><p className="text-sm leading-7 text-[#aaa0d1] md:border-l md:border-white/10 md:pl-8">{t.projects.intro}</p></div>
      <ProjectCard project={featuredProject} featured language={language} labels={t.projects} text={text} />
      <div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{otherProjects.map((project) => <ProjectCard key={project.title} project={project} language={language} labels={t.projects} text={text} />)}</div>
      <div className="reveal mt-16 flex flex-col items-start justify-between gap-5 border-t border-white/10 pt-8 sm:flex-row sm:items-center"><p className="max-w-xl text-sm leading-6 text-white/40">{language === "fr" ? "Chaque projet répond à un contexte différent, avec le même objectif : créer une expérience claire, performante et facile à utiliser." : "Each project answers a different context, with the same goal: create a clear, performant and easy-to-use experience."}</p><a href="#contact" className="group inline-flex items-center gap-2 text-sm font-bold text-white transition hover:text-[#f5d35f]">{language === "fr" ? "Parlons de votre projet" : "Let's discuss your project"}<ArrowUpRight className="h-4 w-4" /></a></div>
    </div>
  </section>;
}

function ProjectCard({ project, featured = false, language, labels, text }: { project: Project; featured?: boolean; language: "fr" | "en"; labels: { cta: string; role: string; result: string; concept: string; code: string }; text: (value: Localized) => string }) {
  return <a href={project.live} target="_blank" rel="noreferrer" className={`reveal group ${featured ? "mt-14 lg:grid lg:grid-cols-[1.3fr_1fr]" : "flex flex-col"} overflow-hidden rounded-[20px] border border-white/10 bg-white/[0.035] transition-colors duration-300 hover:border-[#f5d35f]/30`}>
    <div className={`relative ${featured ? "aspect-[16/10] sm:aspect-[16/9] lg:aspect-auto" : "aspect-[3/2]"} overflow-hidden bg-[#1a1240]`}><Image src={project.image} alt={`${language === "fr" ? "Capture du projet" : "Project screenshot"} ${project.title}`} fill sizes={featured ? "(max-width: 768px) 100vw, 50vw" : "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"} className="object-cover transition duration-500 group-hover:scale-[1.04]" />{project.concept && <span className="absolute left-4 top-4 rounded-full bg-[#f5d35f] px-3 py-1 text-[10px] font-black uppercase tracking-[0.12em] text-[#0d092a]">{labels.concept}</span>}</div>
    <div className="flex flex-1 flex-col gap-4 p-6 sm:p-8"><p className="text-xs font-semibold text-[#f5d35f]">{text(project.category)} — {text(project.type)}</p><h3 className="text-2xl font-black tracking-[-0.03em]">{project.title}</h3><p className="text-sm leading-7 text-[#aaa0d1]">{text(project.description)}</p><dl className="grid gap-2 text-xs leading-5 text-white/65 sm:grid-cols-2"><div><dt className="font-bold uppercase tracking-[0.1em] text-[#f5d35f]">{labels.role}</dt><dd>{text(project.role)}</dd></div><div><dt className="font-bold uppercase tracking-[0.1em] text-[#f5d35f]">{labels.result}</dt><dd>{text(project.result)}</dd></div></dl><div className="mt-auto flex flex-wrap items-center justify-between gap-4 border-t border-white/10 pt-4"><span className="inline-flex items-center gap-1.5 text-xs font-bold text-[#f5d35f]">{labels.cta}<ArrowUpRight className="h-3.5 w-3.5" /></span><div className="flex flex-wrap gap-1.5">{project.stack.map((tech) => <span key={tech} className="rounded-full bg-white/[0.06] px-2.5 py-1 text-[11px] font-medium text-white/60">{tech}</span>)}</div>{project.github && <span role="link" className="inline-flex items-center gap-1.5 text-xs font-medium text-white/60" onClick={(event) => { event.preventDefault(); event.stopPropagation(); window.open(project.github, "_blank", "noopener,noreferrer"); }}><Github className="h-3.5 w-3.5" />{labels.code}</span>}</div></div>
  </a>;
}
